Repository pudding-keep-in-touch/keep-in-touch-be, pull requests merged in 2024-09, with the labels that each got.

#20 emotion 엔티티 추가
  src/entities/emotion-detail.entity.ts
  src/entities/emotions.entity.ts
Labels: enhancement, 1차 개발

#27 쪽지 리스트 조회 api
  src/entities/direct-messages.entity.ts
  src/modules/v1/auth/auth.controller.ts
  src/modules/v1/direct-messages/direct-messages.enum.ts
  src/modules/v1/direct-messages/direct-messages.module.ts
  src/modules/v1/direct-messages/direct-messages.service.ts
  src/modules/v1/direct-messages/dtos/get-dm-list-by-user-id.dto.ts
  src/modules/v1/users/users.controller.ts
  src/modules/v1/users/users.module.ts
  src/modules/v1/users/users.service.ts
  src/repositories/direct-messages.repository.ts
Labels: 1차 개발

#29 홈 api 생성
  src/common/helpers/date.helper.ts
  src/entities/direct-messages.entity.ts
  src/modules/v1/direct-messages/direct-messages.service.ts
  src/modules/v1/direct-messages/dtos/get-dm-list-by-user-id.dto.ts
  src/modules/v1/users/dtos/get-user-home.dto.ts
  src/modules/v1/users/users.controller.ts
  src/modules/v1/users/users.service.ts
  src/repositories/direct-messages.repository.ts
Labels: 1차 개발

#32 유저 탈퇴
  src/entities/emotion-detail.entity.ts
  src/modules/v1/users/user.enum.ts
  src/modules/v1/users/users.controller.ts
  src/modules/v1/users/users.service.ts
  src/repositories/users.repository.ts
Labels: 1차 개발

#34 Feature/33 exception filter
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/common/filters/all-exception.filter.ts
  src/configs/process-env.config.ts
  src/main.ts
Labels: 1차 개발

#36 쪽지 보내기 API 수정
  src/modules/v1/direct-messages/direct-messages.controller.ts
  src/modules/v1/direct-messages/direct-messages.service.ts
  src/modules/v1/direct-messages/dtos/create-dm.dto.ts
Labels: 1차 개발

#38 home api 응답값에 카드 타입 추가
  src/modules/v1/direct-messages/direct-messages.service.ts
  src/modules/v1/users/dtos/get-user-home.dto.ts
  src/modules/v1/users/users.module.ts
  src/modules/v1/users/users.service.ts
  src/repositories/emotions.repository.ts
Labels: 1차 개발

#43 예외처리 추가
  src/modules/v1/direct-messages/direct-messages.service.ts
  src/modules/v1/users/dtos/get-user-home.dto.ts
  src/modules/v1/users/users.service.ts
Labels: bug

#46 에러 핸들링 추가 및 버그 코드 수정
  src/entities/direct-messages.entity.ts
  src/modules/v1/direct-messages/direct-messages.controller.ts
  src/modules/v1/direct-messages/direct-messages.module.ts
  src/modules/v1/direct-messages/direct-messages.service.ts
  src/modules/v1/users/users.module.ts
  src/modules/v1/users/users.service.ts
  src/repositories/direct-messages.repository.ts
Labels: bug

#49 home api에서 email 추가 반환
  src/modules/v1/users/dtos/get-user-home.dto.ts
  src/modules/v1/users/users.service.ts
Labels: 1차 개발

#51 api 테스트
  src/modules/v1/auth/auth.controller.ts
  src/modules/v1/direct-messages/direct-messages.controller.ts
  src/modules/v1/direct-messages/direct-messages.service.ts
  src/modules/v1/users/users.controller.ts
  src/modules/v1/users/users.service.ts
  src/repositories/emotions.repository.ts
Labels: 1차 개발

#53 홈 api 응답값 추가
  src/modules/v1/users/dtos/get-user-home.dto.ts
  src/modules/v1/users/users.controller.ts
  src/modules/v1/users/users.service.ts
  src/repositories/direct-messages.repository.ts
Labels: bug
